apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-hello-world-python-app.name" . }}
  labels:
    {{- include "eric-oss-hello-world-python-app.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "eric-oss-hello-world-python-app.product-info" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  ports:
    - port: {{ index .Values.service "https-port" }}
      targetPort: {{ .Values.service.httpsTargetPort | default 8443 }}
      protocol: TCP
      name: envoy-https
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-hello-world-python-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
